spring:
  keyAlias: authserveralias
  keystorePassword: 0au8Ss@verPa55word
  keyPassword: P@55word
  datasource:
    url: jdbc:postgresql://localhost:5432/auth-server
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
    initialization-mode: always
    platform: postgresql
  jpa:
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create-drop
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true